# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build - All Samples
on:
  push:
    #Change the branch name to <<main>>
    #Change the path to the folder where your code resides. Any change here will start the activity. 
    branches:
      - v-abt/sample-health-build
    paths:
      - 'samples/app-installation-using-qr-code/csharp/**'  
  schedule:
    - cron: '12 21 * * *'  # every day at midnight

jobs:
  build-csharp-samples:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
            - project_path: 'samples/bot-adaptivecards-user-specific-views/csharp/Microsoft.Teams.Samples.UserSpecificViews/Microsoft.Teams.Samples.UserSpecificViews.csproj'
              name: 'bot-adaptivecards-user-specific-views'
              version: '6.0.x'

            - project_path: 'samples/bot-proactive-messaging/csharp/proactive-cmd/msteams-app-proactivecmd.csproj'
              name: 'bot-proactive-messaging'
              version: '3.1.301'

            - project_path: 'samples/bot-sharepoint-list/csharp/SPListBot/SPListBot.csproj'
              name: 'bot-sharepoint-list'
              version: '3.1.301'

            - project_path: 'samples/meetings-share-to-stage-signing/csharp/MeetingSigning.Web/Microsoft.Teams.Samples.MeetingSigning.Web.csproj'
              name: 'meetings-share-to-stage-signing'
              version: '3.1.301'

            - project_path: 'samples/meetings-share-to-stage-signing/csharp/MeetingSigning.Web/Microsoft.Teams.Samples.MeetingSigning.Web.csproj'
              name: 'meetings-share-to-stage-signing'
              version: '3.1.301'

            - project_path: 'samples/tab-channel-group-sso-quickstart/csharp_dotnetcore/GroupTabSSO.csproj'
              name: 'tab-channel-group-sso-quickstart'
              version: '3.1.301'

            - project_path: 'samples/tab-channel-group/mvc-csharp/ChannelGroupTabMVC.csproj'
              name: 'tab-channel-group'
              version: '3.1.301'

            - project_path: 'samples/tab-channel-group/razor-csharp/channelGroupTab.csproj'
              name: 'tab-channel-group'
              version: '3.1.301'

            - project_path: 'samples/tab-personal-sso-quickstart/csharp_dotnetcore/PersonalTabSSO.csproj'
              name: 'tab-personal-sso-quickstart'
              version: '3.1.301'

            - project_path: 'samples/tab-personal/mvc-csharp/PersonalTabMVC.csproj'
              name: 'tab-personal'
              version: '3.1.301'

            - project_path: 'samples/tab-personal/razor-csharp/PersonalTab.csproj'
              name: 'tab-personal'
              version: '3.1.301'

            - project_path: 'samples/graph-chat-lifecycle/csharp/ChatLifecycle/ChatLifecycle.csproj'
              name: 'graph-chat-lifecycle'
              version: '3.1.301'
      fail-fast: false
    name: Build "${{ matrix.name }}" csharp
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ matrix.version }}"
          include-prerelease: true

      - name: Build app
        run: dotnet build "${{ matrix.project_path }}" --configuration Release

  build-dotnet-samples:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
            - project_path: 'samples/app-task-module/csharp/Microsoft.Teams.Samples.TaskModule.sln'
              name: 'app-task-module'

            - project_path: 'samples/connector-todo-notification/csharp/TeamsToDoAppConnector.sln'
              name: 'connector-todo-notification'

            - project_path: 'samples/outgoing-webhook/csharp/WebhookSampleBot.sln'
              name: 'outgoing-webhook'
      fail-fast: false
    name: Build "${{ matrix.name }}" csharp
    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore ${{ matrix.project_path }}
      
      - name: Build
        run: msbuild ${{ matrix.project_path }} /p:Configuration=Release

  build-nodejs-samples:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
            - project_path: 'samples\msgext-search-sso-config'
              name: 'msgext-search-sso-config'
              version: '14.x'

            - project_path: 'samples\meetings-details-tab\nodejs'
              name: 'meetings-details-tab'
              version: '14.x'

            - project_path: 'samples/tab-device-permissions/nodejs'
              name: 'tab-device-permissions'
              version: '14.x'

            - project_path: 'samples/msgext-action-quickstart/js'
              name: 'msgext-action-quickstart'
              version: '14.x'

            - project_path: 'samples/msgext-search-quickstart/js'
              name: 'msgext-search-quickstart'
              version: '14.x'

            - project_path: 'samples/tab-channel-group-quickstart/js'
              name: 'tab-channel-group-quickstart'
              version: '14.x'

            - project_path: 'samples/tab-channel-group-quickstart/ts'
              name: 'tab-channel-group-quickstart'
              version: '14.x'

            - project_path: 'samples/tab-channel-group-sso-quickstart/js'
              name: 'tab-channel-group-sso-quickstart'
              version: '14.x'

            - project_path: 'samples/tab-channel-group-sso-quickstart/ts'
              name: 'tab-channel-group-sso-quickstart'
              version: '14.x'

            - project_path: 'samples/tab-personal-quickstart/js'
              name: 'tab-personal-quickstart'
              version: '14.x'

            - project_path: 'samples/tab-personal-quickstart/ts'
              name: 'tab-personal-quickstart'
              version: '14.x'

            - project_path: 'samples/tab-personal-sso-quickstart/js'
              name: 'tab-personal-sso-quickstart'
              version: '14.x'

            - project_path: 'samples/tab-personal-sso-quickstart/ts'
              name: 'tab-personal-sso-quickstart'
              version: '14.x'

            - project_path: 'samples/app-localization/nodejs'
              name: 'app-localization'
              version: '14.x'

            - project_path: 'samples/tab-graph-toolkit/nodejs'
              name: 'tab-graph-toolkit'
              version: '14.x'
      fail-fast: false
    name: Build "${{ matrix.name }}" nodejs
    defaults:
      run:
        working-directory: "${{ matrix.project_path }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.version }}"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
    
