# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build - All Samples
on:
  push:
    #Change the branch name to <<main>>
    #Change the path to the folder where your code resides. Any change here will start the activity. 
    branches:
      - v-abt/sample-health-build
    paths:
      - 'samples/app-installation-using-qr-code/csharp/**'  
  schedule:
    - cron: '12 21 * * *'  # every day at midnight
env:
    PROJECT_PATH_APP_VIRTUAL_ASSISTANT_CSHARP: ''

jobs:
  build-csharp-samples:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
            - project_path: 'samples/app-complete-sample/csharp/template-bot-master-csharp/template-bot-master-csharp.csproj'
              name: 'app-complete-sample'
              version: '3.1.301'

            - project_path: 'samples/app-region-selection/csharp/RegionSectionApp/RegionSectionApp.csproj'
              name: 'app-region-selection'
              version: '3.1.301'

            - project_path: 'samples/app-task-module/csharp/Microsoft.Teams.Samples.TaskModule.Web/Microsoft.Teams.Samples.TaskModule.Web.csproj'
              name: 'app-task-module'
              version: '3.1.301'

            - project_path: 'samples/graph-activity-feed-broadcast/csharp/ActivityFeedBroadcast/ActivityFeedBroadcast.csproj'
              name: 'graph-activity-feed-broadcast'
              version: '3.1.301'

            - project_path: 'samples/graph-app-installation-lifecycle/csharp/AppInstallation/AppInstallation.csproj'
              name: 'graph-app-installation-lifecycle'
              version: '3.1.301'

            - project_path: 'samples/graph-appcatalog-lifecycle/csharp/AppCatalogSample/AppCatalogSample.csproj'
              name: 'graph-appcatalog-lifecycle'
              version: '3.1.301'

            - project_path: 'samples/graph-change-notification/csharp/ChangeNotification/ChangeNotification.csproj'
              name: 'graph-change-notification'
              version: '3.1.301'

            - project_path: 'samples/graph-channel-lifecycle/csharp/ChannelLifecycle/ChannelLifecycle.csproj'
              name: 'graph-channel-lifecycle'
              version: '3.1.301'

            - project_path: 'samples/graph-chat-lifecycle/csharp/ChatLifecycle/ChatLifecycle.csproj'
              name: 'graph-chat-lifecycle'
              version: '3.1.301'

            - project_path: 'samples/graph-proactive-installation/csharp/ProactiveAppInstallation/ProactiveAppInstallation.csproj'
              name: 'graph-proactive-installation'
              version: '3.1.301'

            - project_path: 'samples/graph-rsc/csharp/RSCDemo/RSCDemo.csproj'
              name: 'graph-rsc'
              version: '3.1.301'

            - project_path: 'samples/meeting-recruitment-app/csharp/MeetingApp/MeetingApp.csproj'
              name: 'meeting-recruitment-app'
              version: '3.1.301'

            - project_path: 'samples/meetings-content-bubble/csharp/ContentBubble/Content Bubble Bot.csproj'
              name: 'meetings-content-bubble'
              version: '3.1.301'

            - project_path: 'samples/meetings-details-tab/csharp/DetailsTab/DetailsTab.csproj'
              name: 'meetings-details-tab'
              version: '3.1.301'

            - project_path: 'samples/meetings-live-code-interview/csharp/MeetingLiveCoding/MeetingLiveCoding.csproj'
              name: 'meetings-live-code-interview'
              version: '3.1.301'

            - project_path: 'samples/meetings-sidepanel/csharp/SidePanel/SidePanel.csproj'
              name: 'meetings-sidepanel'
              version: '3.1.301'

            - project_path: 'samples/meetings-stage-view/csharp/AppInMeeting/AppInMeeting.csproj'
              name: 'meetings-stage-view'
              version: '3.1.301'

            - project_path: 'samples/meetings-token-app/csharp/TokenApp.csproj'
              name: 'meetings-token-app'
              version: '3.1.301'

            - project_path: 'samples/msgext-link-unfurling-meeting/csharp/Source/Microsoft.Teams.Samples.LinkUnfurling.Web./Microsoft.Teams.Samples.LinkUnfurling.Web.csproj'
              name: 'msgext-link-unfurling-meeting'
              version: '3.1.301'

            - project_path: 'samples/msgext-link-unfurling-reddit/csharp/dotnet/RLU.csproj'
              name: 'msgext-link-unfurling-reddit'
              version: '2.1.x'

      fail-fast: false
    name: Build "${{ matrix.name }}" csharp
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ matrix.version }}"
          include-prerelease: true

      - name: Build app
        run: dotnet build "${{ matrix.project_path }}" --configuration Release

  build-nodejs-samples:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
            - project_path: 'samples/app-localization/nodejs'
              name: 'app-localization'
              version: '14.x'

            - project_path: 'samples/graph-activity-feed-broadcast/nodejs'
              name: 'graph-activity-feed-broadcast'
              version: '14.x'

            - project_path: 'samples/graph-activity-feed/nodejs'
              name: 'graph-activity-feed'
              version: '14.x'

            - project_path: 'samples/graph-app-installation-lifecycle/nodejs'
              name: 'graph-app-installation-lifecycle'
              version: '14.x'

            - project_path: 'samples/graph-appcatalog-lifecycle/nodejs'
              name: 'graph-appcatalog-lifecycle'
              version: '14.x'

            - project_path: 'samples/graph-change-notification/nodejs'
              name: 'graph-change-notification'
              version: '14.x'

            - project_path: 'samples/graph-channel-lifecycle/nodejs'
              name: 'graph-channel-lifecycle'
              version: '14.x'

            - project_path: 'samples/graph-chat-lifecycle/nodejs'
              name: 'graph-chat-lifecycle'
              version: '14.x'

            - project_path: 'samples/graph-proactive-installation/nodejs'
              name: 'graph-proactive-installation'
              version: '14.x'

            - project_path: 'samples/graph-rsc/nodejs'
              name: 'graph-rsc'
              version: '14.x'

            - project_path: 'samples/meeting-recruitment-app/nodejs'
              name: 'meeting-recruitment-app'
              version: '14.x'

            - project_path: 'samples/meetings-content-bubble/nodejs'
              name: 'meetings-content-bubblek'
              version: '14.x'

            - project_path: 'samples/meetings-details-tab/nodejs'
              name: 'meetings-details-tab'
              version: '14.x'

            - project_path: 'samples/meetings-events/nodejs'
              name: 'meetings-events'
              version: '14.x'

            - project_path: 'samples/meetings-live-code-interview/nodejs'
              name: 'meetings-live-code-interview'
              version: '14.x'

            - project_path: 'samples/meetings-sidepanel/nodejs'
              name: 'meetings-sidepanel'
              version: '14.x'

            - project_path: 'samples/meetings-stage-view/nodejs'
              name: 'meetings-stage-view'
              version: '14.x'

            - project_path: 'samples/meetings-token-app/nodejs'
              name: 'meetings-token-app'
              version: '14.x'

      fail-fast: false
    name: Build "${{ matrix.name }}" nodejs
    defaults:
      run:
        working-directory: "${{ matrix.project_path }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.version }}"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
    
